CREATE TABLE users (
 id uuid PRIMARY KEY, slot text NOT NULL UNIQUE CHECK(slot IN ('owner','partner')),
 username text NOT NULL UNIQUE CHECK(username=lower(username)), display_name text NOT NULL,
 role text NOT NULL CHECK((slot='owner' AND role='OWNER') OR (slot='partner' AND role='PARTNER')),
 password_hash text NOT NULL, must_change_password boolean NOT NULL DEFAULT true,
 disabled_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), avatar_asset_id uuid,
 preferences_json jsonb NOT NULL DEFAULT '{}', CHECK(slot<>'owner' OR disabled_at IS NULL)
);
CREATE TABLE sessions(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id),token_hash text NOT NULL UNIQUE,csrf_hash text NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),last_seen_at timestamptz NOT NULL DEFAULT now(),absolute_expires_at timestamptz NOT NULL,revoked_at timestamptz,auth_time timestamptz NOT NULL DEFAULT now(),device_label text NOT NULL);
CREATE INDEX sessions_user ON sessions(user_id,revoked_at,absolute_expires_at);
CREATE TABLE reset_tokens(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id),token_hash text UNIQUE NOT NULL,expires_at timestamptz NOT NULL,used_at timestamptz);
CREATE TABLE categories(id uuid PRIMARY KEY,name text NOT NULL,normalized_name text UNIQUE NOT NULL,sort_order integer NOT NULL DEFAULT 0);
CREATE TABLE media(id uuid PRIMARY KEY,title text NOT NULL,description text NOT NULL DEFAULT '',category_id uuid REFERENCES categories(id),poster_asset_id uuid,primary_source_id uuid,content_generation uuid NOT NULL,duration_seconds double precision NOT NULL DEFAULT 0 CHECK(duration_seconds>=0 AND duration_seconds<'Infinity'::float8),publication_state text NOT NULL DEFAULT 'DRAFT' CHECK(publication_state IN ('DRAFT','PUBLISHED','WITHDRAWN')),created_by uuid NOT NULL REFERENCES users(id),created_at timestamptz NOT NULL DEFAULT now(),updated_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz);
CREATE TABLE provider_connections(id uuid PRIMARY KEY,provider text NOT NULL CHECK(provider='drive'),owner_id uuid NOT NULL REFERENCES users(id),encrypted_secrets jsonb NOT NULL,encryption_key_version integer NOT NULL DEFAULT 1,status text NOT NULL,scopes_json jsonb NOT NULL DEFAULT '[]',authorized_at timestamptz,last_verified_at timestamptz,safe_error_code text);
CREATE UNIQUE INDEX drive_owner ON provider_connections(provider,owner_id);
CREATE TABLE sources(id uuid PRIMARY KEY,media_id uuid NOT NULL REFERENCES media(id),kind text NOT NULL CHECK(kind IN ('local','http_file','hls','dash','drive')),encrypted_reference jsonb NOT NULL,connection_id uuid REFERENCES provider_connections(id),delivery_strategy text NOT NULL CHECK(delivery_strategy IN ('direct','relay')),health text NOT NULL DEFAULT 'UNCHECKED' CHECK(health IN ('UNCHECKED','CHECKING','READY','EXPIRED','AUTH_REQUIRED','UNSUPPORTED','UNAVAILABLE','ERROR')),content_fingerprint text,last_checked_at timestamptz,capabilities_json jsonb NOT NULL DEFAULT '{}',safe_error_code text,approved_origins_json jsonb NOT NULL DEFAULT '[]');
ALTER TABLE media ADD CONSTRAINT media_primary_source_fk FOREIGN KEY(primary_source_id) REFERENCES sources(id) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE assets(id uuid PRIMARY KEY,media_id uuid REFERENCES media(id),kind text NOT NULL CHECK(kind IN ('original','compatible','poster','subtitle','sprite','chapters','hls','dash','avatar')),storage_key text NOT NULL UNIQUE,mime_type text NOT NULL,bytes bigint NOT NULL CHECK(bytes>=0),checksum text NOT NULL,metadata_json jsonb NOT NULL DEFAULT '{}',state text NOT NULL DEFAULT 'READY');
ALTER TABLE media ADD CONSTRAINT media_poster_fk FOREIGN KEY(poster_asset_id) REFERENCES assets(id);
ALTER TABLE users ADD CONSTRAINT user_avatar_fk FOREIGN KEY(avatar_asset_id) REFERENCES assets(id);
CREATE TABLE subtitles(id uuid PRIMARY KEY,media_id uuid NOT NULL REFERENCES media(id),asset_id uuid NOT NULL REFERENCES assets(id),language_tag text NOT NULL,label text NOT NULL,is_default boolean NOT NULL DEFAULT false);
CREATE TABLE chapters(id uuid PRIMARY KEY,media_id uuid NOT NULL REFERENCES media(id),start_seconds double precision NOT NULL CHECK(start_seconds>=0 AND start_seconds<'Infinity'::float8),title text NOT NULL,sort_order integer NOT NULL,UNIQUE(media_id,sort_order));
CREATE TABLE watchlist(media_id uuid PRIMARY KEY REFERENCES media(id),added_by uuid NOT NULL REFERENCES users(id),added_at timestamptz NOT NULL DEFAULT now(),marked_watched_at timestamptz);
CREATE TABLE solo_sessions(id uuid PRIMARY KEY,user_id uuid NOT NULL REFERENCES users(id),media_id uuid NOT NULL REFERENCES media(id),content_generation uuid NOT NULL,client_instance_id uuid NOT NULL,write_revision bigint NOT NULL DEFAULT 0,ended_at timestamptz);
CREATE UNIQUE INDEX solo_current ON solo_sessions(user_id,media_id) WHERE ended_at IS NULL;
CREATE TABLE user_progress(user_id uuid NOT NULL REFERENCES users(id),media_id uuid NOT NULL REFERENCES media(id),content_generation uuid NOT NULL,position_seconds double precision NOT NULL CHECK(position_seconds>=0 AND position_seconds<'Infinity'::float8),completed_at timestamptz,solo_session_id uuid REFERENCES solo_sessions(id),write_revision bigint NOT NULL,updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(user_id,media_id,content_generation));
CREATE TABLE rooms(id uuid PRIMARY KEY,singleton_key text NOT NULL UNIQUE CHECK(singleton_key='home'),active_session_id uuid,revision bigint NOT NULL DEFAULT 0,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE viewing_sessions(id uuid PRIMARY KEY,room_id uuid NOT NULL REFERENCES rooms(id),state_json jsonb NOT NULL,host_user_id uuid NOT NULL REFERENCES users(id),host_epoch bigint NOT NULL,last_checkpoint_position double precision NOT NULL DEFAULT 0,started_at timestamptz NOT NULL DEFAULT now(),ended_at timestamptz);
CREATE UNIQUE INDEX one_active_session ON viewing_sessions(room_id) WHERE ended_at IS NULL;
ALTER TABLE rooms ADD CONSTRAINT room_active_session_fk FOREIGN KEY(active_session_id) REFERENCES viewing_sessions(id) DEFERRABLE INITIALLY DEFERRED;
CREATE TABLE shared_progress(media_id uuid NOT NULL REFERENCES media(id),content_generation uuid NOT NULL,position_seconds double precision NOT NULL CHECK(position_seconds>=0 AND position_seconds<'Infinity'::float8),completed_at timestamptz,viewing_session_id uuid REFERENCES viewing_sessions(id),updated_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(media_id,content_generation));
CREATE TABLE playback_leases(user_id uuid PRIMARY KEY REFERENCES users(id),room_id uuid NOT NULL REFERENCES rooms(id),session_id uuid REFERENCES viewing_sessions(id),auth_session_id uuid NOT NULL REFERENCES sessions(id),lease_hash text NOT NULL,client_instance_id uuid NOT NULL,expires_at timestamptz NOT NULL,revoked_at timestamptz,status text NOT NULL DEFAULT 'present',last_report_json jsonb NOT NULL DEFAULT '{}');
CREATE TABLE command_receipts(actor_user_id uuid NOT NULL REFERENCES users(id),command_id uuid NOT NULL,payload_hash text NOT NULL,session_id uuid NOT NULL REFERENCES viewing_sessions(id),accepted_revision bigint NOT NULL,result_json jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(actor_user_id,command_id));
CREATE TABLE chat_messages(id uuid PRIMARY KEY,room_id uuid NOT NULL REFERENCES rooms(id),sender_id uuid NOT NULL REFERENCES users(id),client_message_id uuid NOT NULL,seq bigint GENERATED ALWAYS AS IDENTITY,body text CHECK(char_length(body)<=2000),created_at timestamptz NOT NULL DEFAULT now(),deleted_at timestamptz,UNIQUE(sender_id,client_message_id),UNIQUE(room_id,seq));
CREATE TABLE uploads(id uuid PRIMARY KEY,owner_id uuid NOT NULL REFERENCES users(id),expected_bytes bigint NOT NULL CHECK(expected_bytes>0),committed_offset bigint NOT NULL DEFAULT 0 CHECK(committed_offset>=0 AND committed_offset<=expected_bytes),original_name text NOT NULL,temporary_key text NOT NULL UNIQUE,state text NOT NULL DEFAULT 'uploading',expires_at timestamptz NOT NULL,media_id uuid REFERENCES media(id));
CREATE TABLE jobs(id uuid PRIMARY KEY,kind text NOT NULL,media_id uuid REFERENCES media(id),payload_json jsonb NOT NULL DEFAULT '{}',unique_key text NOT NULL UNIQUE,state text NOT NULL DEFAULT 'queued' CHECK(state IN ('queued','running','succeeded','failed','cancelled')),attempt integer NOT NULL DEFAULT 0,max_attempts integer NOT NULL DEFAULT 3,run_after timestamptz NOT NULL DEFAULT now(),lease_owner text,lease_until timestamptz,progress double precision NOT NULL DEFAULT 0 CHECK(progress>=0 AND progress<=1),safe_error_code text,cancel_requested boolean NOT NULL DEFAULT false,created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE audit_events(id uuid PRIMARY KEY,actor_id uuid REFERENCES users(id),action text NOT NULL,target_type text,target_id uuid,correlation_id text,safe_details_json jsonb NOT NULL DEFAULT '{}',created_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE settings(key text PRIMARY KEY,value_json jsonb NOT NULL,updated_at timestamptz NOT NULL DEFAULT now());
CREATE TABLE oauth_states(id uuid PRIMARY KEY,state_hash text UNIQUE NOT NULL,auth_session_id uuid NOT NULL REFERENCES sessions(id),expires_at timestamptz NOT NULL,used_at timestamptz);
CREATE TABLE http_receipts(actor_user_id uuid NOT NULL REFERENCES users(id),request_key uuid NOT NULL,operation text NOT NULL,payload_hash text NOT NULL,result_json jsonb NOT NULL,created_at timestamptz NOT NULL DEFAULT now(),PRIMARY KEY(actor_user_id,request_key));
CREATE FUNCTION guard_published_media() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN
 IF NEW.publication_state='PUBLISHED' AND NOT EXISTS(SELECT 1 FROM sources WHERE id=NEW.primary_source_id AND media_id=NEW.id AND health='READY') THEN RAISE EXCEPTION 'Published media requires its own ready source'; END IF; RETURN NEW; END $$;
CREATE TRIGGER valid_published_media BEFORE INSERT OR UPDATE OF publication_state,primary_source_id ON media FOR EACH ROW EXECUTE FUNCTION guard_published_media();
